version: '2.1'
services:
    redis:
        image: 'redis:5.0.5'
        networks:
            - cda        
        command: redis-server --requirepass redispass

    postgres:
        image: postgres:9.6
        networks:
            - cda        
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
             - ./pgdata:/var/lib/postgresql/data/pgdata

    webserver:
        # image: puckel/docker-airflow:1.10.9
        build: .
        restart: always
        networks:
            - cda        
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=y
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
            - SPARK_HOME=/usr/local/spark
            - HADOOP_CONF_DIR=/usr/local/spark/conf
        volumes:
            - /dock/dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
        ports:
            - "8181:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: puckel/docker-airflow:1.10.9
        restart: always
        networks:
            - cda        
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            - REDIS_PASSWORD=redispass
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        # image: puckel/docker-airflow:1.10.9
        build: .
        restart: always
        networks:
            - cda        
        depends_on:
            - webserver
        volumes:
            - /dock/dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
            - SPARK_HOME=/usr/local/spark
            - HADOOP_CONF_DIR=/usr/local/spark/conf
        command: scheduler

    worker:
        # image: puckel/docker-airflow:1.10.9
        build: .
        restart: always
        networks:
            - cda        
        depends_on:
            - scheduler
        volumes:
            - /dock/dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # ./plugins:/usr/local/airflow/plugins
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
            - SPARK_HOME=/usr/local/spark
            - HADOOP_CONF_DIR=/usr/local/spark/conf
        command: worker

networks:
    cda:
        external:
            name: cda